import 'package:flutter/material.dart';

class AppStrings {
  const AppStrings._(this.locale);

  final Locale locale;

  static const supportedLocales = [
    Locale('en'),
    Locale('mr'),
    Locale('hi'),
  ];

  static const _values = <String, Map<String, String>>{
    'en': {
      'appName': 'Satva Dhara ERP',
      'dashboard': 'Dashboard',
      'animals': 'Animals',
      'milk': 'Milk',
      'health': 'Health',
      'breeding': 'Breeding',
      'pregnancy': 'Pregnancy',
      'feed': 'Feed',
      'inventory': 'Inventory',
      'finance': 'Finance',
      'customers': 'Customers',
      'suppliers': 'Suppliers',
      'staff': 'Staff',
      'tasks': 'Tasks',
      'assets': 'Assets',
      'reports': 'Reports',
      'ai': 'AI Farm Brain',
      'settings': 'Settings',
      'main': 'MAIN',
      'operations': 'OPERATIONS',
      'business': 'BUSINESS',
      'intelligence': 'INTELLIGENCE',
      'system': 'SYSTEM',
      'welcomeTitle': 'Your farm operating system.',
      'welcomeSubtitle': 'One place to record, understand and act.',
      'today': 'Today',
      'production': 'Production',
      'revenue': 'Revenue',
      'expenses': 'Expenses',
      'attention': 'Needs attention',
      'noData': 'No farm data yet',
      'noDataText': 'Connect your farm data in the next setup phase. No sample numbers are shown.',
      'foundation': 'Phase 1 Foundation',
      'foundationText': 'Branding, design system, routing and responsive shell are ready. Business modules will be added without changing the foundation architecture.',
      'firebaseReady': 'Firebase connected',
      'firebaseSetup': 'Firebase setup required',
      'logout': 'Sign out',
      'searchHint': 'Search animals, milk, health, finance...',
      'language': 'Language',
      'english': 'English',
      'marathi': 'मराठी',
      'hindi': 'हिन्दी',
      'openModule': 'Open module',
    },
    'mr': {
      'appName': 'सत्व धारा ERP',
      'dashboard': 'डॅशबोर्ड',
      'animals': 'जनावरे',
      'milk': 'दूध',
      'health': 'आरोग्य',
      'breeding': 'प्रजनन',
      'pregnancy': 'गर्भावस्था',
      'feed': 'खाद्य',
      'inventory': 'साठा',
      'finance': 'अर्थकारण',
      'customers': 'ग्राहक',
      'suppliers': 'पुरवठादार',
      'staff': 'कर्मचारी',
      'tasks': 'कामे',
      'assets': 'मालमत्ता',
      'reports': 'अहवाल',
      'ai': 'AI Farm Brain',
      'settings': 'सेटिंग्ज',
      'main': 'मुख्य',
      'operations': 'ऑपरेशन्स',
      'business': 'व्यवसाय',
      'intelligence': 'इंटेलिजन्स',
      'system': 'सिस्टम',
      'welcomeTitle': 'तुमच्या फार्मचे operating system.',
      'welcomeSubtitle': 'नोंद, विश्लेषण आणि कृती — एकाच ठिकाणी.',
      'today': 'आज',
      'production': 'उत्पादन',
      'revenue': 'उत्पन्न',
      'expenses': 'खर्च',
      'attention': 'लक्ष आवश्यक',
      'noData': 'अजून फार्म डेटा नाही',
      'noDataText': 'पुढील setup phase मध्ये तुमचा farm data जोडला जाईल. येथे बनावट आकडे दाखवले जाणार नाहीत.',
      'foundation': 'Phase 1 Foundation',
      'foundationText': 'Branding, design system, routing आणि responsive shell तयार आहे. पुढील business modules याच architecture वर जोडले जातील.',
      'firebaseReady': 'Firebase जोडलेले आहे',
      'firebaseSetup': 'Firebase setup आवश्यक',
      'logout': 'Sign out',
      'searchHint': 'जनावरे, दूध, आरोग्य, finance शोधा...',
      'language': 'भाषा',
      'english': 'English',
      'marathi': 'मराठी',
      'hindi': 'हिन्दी',
      'openModule': 'Module उघडा',
    },
    'hi': {
      'appName': 'सत्व धारा ERP',
      'dashboard': 'डैशबोर्ड',
      'animals': 'पशु',
      'milk': 'दूध',
      'health': 'स्वास्थ्य',
      'breeding': 'प्रजनन',
      'pregnancy': 'गर्भावस्था',
      'feed': 'चारा',
      'inventory': 'स्टॉक',
      'finance': 'वित्त',
      'customers': 'ग्राहक',
      'suppliers': 'आपूर्तिकर्ता',
      'staff': 'स्टाफ',
      'tasks': 'कार्य',
      'assets': 'संपत्तियां',
      'reports': 'रिपोर्ट',
      'ai': 'AI Farm Brain',
      'settings': 'सेटिंग्स',
      'main': 'मुख्य',
      'operations': 'ऑपरेशंस',
      'business': 'व्यवसाय',
      'intelligence': 'इंटेलिजेंस',
      'system': 'सिस्टम',
      'welcomeTitle': 'आपके फार्म का operating system.',
      'welcomeSubtitle': 'रिकॉर्ड, समझ और कार्रवाई — एक ही जगह।',
      'today': 'आज',
      'production': 'उत्पादन',
      'revenue': 'आय',
      'expenses': 'खर्च',
      'attention': 'ध्यान आवश्यक',
      'noData': 'अभी फार्म डेटा नहीं है',
      'noDataText': 'अगले setup phase में आपका farm data जोड़ा जाएगा। यहां नकली आंकड़े नहीं दिखाए जाएंगे।',
      'foundation': 'Phase 1 Foundation',
      'foundationText': 'Branding, design system, routing और responsive shell तैयार है। बाकी business modules इसी architecture पर जोड़े जाएंगे।',
      'firebaseReady': 'Firebase जुड़ा है',
      'firebaseSetup': 'Firebase setup आवश्यक',
      'logout': 'Sign out',
      'searchHint': 'पशु, दूध, स्वास्थ्य, finance खोजें...',
      'language': 'भाषा',
      'english': 'English',
      'marathi': 'मराठी',
      'hindi': 'हिन्दी',
      'openModule': 'Module खोलें',
    },
  };

  String get(String key) {
    final language = _values[locale.languageCode] ?? _values['en']!;
    return language[key] ?? _values['en']![key] ?? key;
  }

  static AppStrings of(BuildContext context) {
    final locale = Localizations.localeOf(context);
    return AppStrings._(locale);
  }
}
